Repository puppetlabs/puppetlabs-stdlib, pull requests merged in 2018-12, with the labels that each got.

#974 (maint) - Add HTML anchor tag
  README.md
Labels: maintenance

#971 (MODULES-8273) - Make unquoted classes useable
  lib/puppet/parser/functions/defined_with_params.rb
  spec/acceptance/defined_with_params_spec.rb
  spec/functions/defined_with_params_spec.rb
Labels: feature

#977 pdksync - pdksync_heads/master-0-gbf720df
  .gitattributes
  .pdkignore
  .puppet-lint.rc
  .travis.yml
  Rakefile
  metadata.json
  spec/default_facts.yml
  spec/spec_helper.rb
Labels: maintenance

#978 (MODULES-8137) - Addition of support for SLES 15
  metadata.json
Labels: feature

#979 pdksync - (FM-7655) Fix rubygems-update for ruby < 2.3
  .travis.yml
  metadata.json
Labels: bugfix
