Repository puppetlabs/puppetlabs-stdlib, pull requests merged in 2019-12, with the labels that each got.

#1070 pdksync - FM-8499 remove ubuntu 14 support
  metadata.json
  provision.yaml
Labels: backwards-incompatible

#1071 pdksync - "MODULES-10242 Add ubuntu14 support back to the modules"
  metadata.json
  provision.yaml
Labels: feature

#1072 pdksync - "MODULES-10236 disable deploy_to_forge for the module"
  .sync.yml
  .travis.yml
  metadata.json
Labels: maintenance

#1056 Add pending tests for to_json_pretty with skip_undef enabled
  spec/functions/to_json_pretty_spec.rb
Labels: maintenance

#1074 pdksync - (maint) travis updates: bundler and slack
  .sync.yml
  .travis.yml
  metadata.json
Labels: maintenance

#1076 pdksync - FM-8834 - Add GitHub action workflow
  .github/workflows/release.yml
Labels: maintenance
