Repository puppetlabs/puppetlabs-stdlib, pull requests merged in 2019-07, with the labels that each got.

#1031 (FM-8230) Convert testing to litmus
  .fixtures.yml
  .rubocop.yml
  .sync.yml
  .travis.yml
  Gemfile
  Rakefile
  appveyor.yml
  distelli-manifest.yml
  metadata.json
  provision.yaml
  spec/acceptance/anchor_spec.rb
  spec/acceptance/build_csv.rb
  spec/acceptance/file_line_spec.rb
  spec/acceptance/has_interface_with_spec.rb
  spec/acceptance/is_a_spec.rb
  spec/acceptance/is_mac_address_spec.rb
  spec/acceptance/pw_hash_spec.rb
  spec/acceptance/size_spec.rb
  spec/acceptance/strftime_spec.rb
  spec/acceptance/type3x_spec.rb
  spec/acceptance/type_spec.rb
  spec/acceptance/validate_augeas_spec.rb
  spec/acceptance/validate_cmd_spec.rb
  spec/functions/load_module_metadata_spec.rb
  spec/functions/loadjson_spec.rb
  spec/functions/strftime_spec.rb
  spec/spec_helper_acceptance.rb
Labels: feature

#1035 pdksync - pdksync_heads/master-0-gb096033
  metadata.json
  spec/spec_helper.rb
Labels: maintenance

#1037 Fix typo in abs function
  lib/puppet/parser/functions/abs.rb
Labels: maintenance

#1023 Limit the maximum array size produced by range().
  lib/puppet/parser/functions/range.rb
Labels: bugfix

#1029 fix lib/puppet/parser/functions/fqdn_rand_string.rb:21: syntax error
  lib/puppet/parser/functions/fqdn_rand_string.rb
Labels: bugfix
