Repository puppetlabs/puppetlabs-stdlib, pull requests merged in 2019-04, with the labels that each got.

#1011 pdksync - (MODULES-8444) - Raise lower Puppet bound
  metadata.json
Labels: backwards-incompatible

#1003 Add a stdlib::ip_in_range() function
  README.md
  lib/puppet/functions/stdlib/ip_in_range.rb
  spec/functions/ip_in_range_spec.rb
Labels: feature

#1012 pdksync - (maint) Update pdk-template to f778803
  .gitignore
  .pdkignore
  .puppet-lint.rc
  .travis.yml
  appveyor.yml
  metadata.json
Labels: maintenance
