Repository puppetlabs/puppetlabs-stdlib, pull requests merged in 2019-01, with the labels that each got.

#982 pdksync - pdksync_heads/master-0-g9c815ea
  .travis.yml
  metadata.json
Labels: maintenance

#980 Creates new type Stdlib::IP::Address::V6::CIDR
  README.md
  spec/type_aliases/ip_address_v6_cidr_spec.rb
  types/ip/address/v6/cidr.pp
Labels: feature

#983 pdksync - pdksync_heads/master-0-g6814a87
  .travis.yml
  Gemfile
  appveyor.yml
  metadata.json
Labels: maintenance

#992 (MODULES-8478) - 5.2.0 Release Preparation
  CHANGELOG.md
  metadata.json
Labels: maintenance

#993 (maint) - 5.2.0 Release mergeback
  CHANGELOG.md
  metadata.json
Labels: maintenance

#996 pdksync - pdksync_1.9.0-0-g7281db5
  .puppet-lint.rc
  metadata.json
  spec/spec_helper.rb
Labels: maintenance

#994 (FM-7724) - Remove Windows 8 testing/support
  metadata.json
Labels: backwards-incompatible

#995 (FM-7720/FM-7722/FM-7723) Consolidate Windows Metadata
  metadata.json
Labels: bugfix
