Repository puppetlabs/puppetlabs-stdlib, pull requests merged in 2020-08, with the labels that each got.

#1117 pdksync - (IAC-973) - Update travis/appveyor to run on new default branch `main`
  .travis.yml
  Rakefile
  appveyor.yml
  metadata.json
Labels: feature

#1115 [MODULES-10729] defined_with_params - unnamed type
  lib/puppet/parser/functions/defined_with_params.rb
  spec/functions/defined_with_params_spec.rb
Labels: bugfix

#1122 [MODULES-10781] Fix defined type defined_with_params()
  lib/puppet/parser/functions/defined_with_params.rb
  spec/functions/defined_with_params_spec.rb
Labels: bugfix

#1123 (maint) - Merge PRs mistakenly merged into master into main
  lib/puppet/parser/functions/defined_with_params.rb
  spec/functions/defined_with_params_spec.rb
Labels: maintenance
