Repository puppetlabs/puppetlabs-stdlib, pull requests merged in 2021-02, with the labels that each got.

#1158 Release prep for version v6.6.0
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance

#1159 (IAC-1412) Release mergeback v6.6.0
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance

#1162 (IAC-1228) Fix multiple spec test issues in Ruby 2.7
  spec/functions/load_module_metadata_spec.rb
  spec/functions/loadjson_spec.rb
  spec/functions/shell_escape_spec.rb
  spec/functions/shell_join_spec.rb
Labels: maintenance

#1161 (IAC-1414) Throw error in range() function when step size invalid
  lib/puppet/parser/functions/range.rb
Labels: bugfix

#1160 Stdlib::Email type
  spec/type_aliases/email_spec.rb
  types/email.pp
Labels: feature

#1163 (bugfix) Setting stricter email validation
  spec/type_aliases/email_spec.rb
  types/email.pp
Labels: bugfix

#1167 pdksync - (MAINT) Remove RHEL 5 family support
  metadata.json
Labels: maintenance

#1168 pdksync - (MAINT) Remove SLES 11 support
  metadata.json
Labels: maintenance

#1169 pdksync - (MAINT) PDK update for GHA workflows + Litmus updates
  .github/workflows/nightly.yml
  .github/workflows/pr_test.yml
  .rubocop.yml
  .travis.yml
  Rakefile
  appveyor.yml
  metadata.json
Labels: maintenance
