Repository puppetlabs/puppetlabs-stdlib, pull requests merged in 2021-03, with the labels that each got.

#1164 pdksync - Remove Puppet 5 from testing and bump minimal version to 6.0.0
  .github/workflows/auto_release.yml
  .sync.yml
  .travis.yml
  metadata.json
  provision.yaml
Labels: backwards-incompatible

#1170 Release prep v7.0.0
  CHANGELOG.md
  metadata.json
Labels: maintenance

#1171 Release Merge Back PR v7.0.0
  CHANGELOG.md
  metadata.json
Labels: maintenance

#1172 Use fork of github_changelog_generator that allows generator to continue on errors
  Gemfile
  Rakefile
Labels: maintenance

#1176 Fix typo in validate_ipv6_address function
  lib/puppet/parser/functions/validate_ipv6_address.rb
Labels: bugfix

#1175 pdksync - PDK Update - Replace Travis and Appveyor with Github Actions
  .github/workflows/auto_release.yml
  .github/workflows/nightly.yml
  .github/workflows/pr_test.yml
  .github/workflows/release.yml
  .github/workflows/spec.yml
  .pdkignore
  .sync.yml
  .travis.yml
  appveyor.yml
  metadata.json
Labels: maintenance
