Repository puppetlabs/puppetlabs-stdlib, pull requests merged in 2021-08, with the labels that each got.

#1199 pdksync - (IAC-1709) - Add Support for Debian 11
  metadata.json
Labels: feature

#1196 Fix ensure_packages
  lib/puppet/parser/functions/ensure_packages.rb
  spec/functions/ensure_packages_spec.rb
Labels: bugfix

#1201 (maint) - Set max_issues for changelog generator to 500
  .github/workflows/auto_release.yml
  .github/workflows/pr_test.yml
  .github/workflows/spec.yml
  .sync.yml
  Rakefile
  metadata.json
Labels: maintenance

#1207 os_version_gte: fix version comparison logic
  lib/puppet/functions/os_version_gte.rb
  spec/functions/os_version_gte_spec.rb
Labels: bugfix
