Repository puppetlabs/puppetlabs-stdlib, pull requests merged in 2022-08, with the labels that each got.

#1261 pdksync - (GH-cat-11) Certify Support for Ubuntu 22.04
  metadata.json
Labels: feature

#1263 Fix spelling
  README.md
Labels: community

#1264 (GH-1262) Use 'require_relative' to load stdlib due to lookup errors
  lib/puppet_x/stdlib/toml_dumper.rb
  spec/functions/loadjson_spec.rb
Labels: bugfix
