Repository puppetlabs/puppetlabs-stdlib, pull requests merged in 2022-04, with the labels that each got.

#1229 pdksync - PDKSYNC Update labeller trigger
  .github/workflows/labeller.yml
Labels: maintenance

#1231 Fix `to_yaml` `options` parameter
  REFERENCE.md
  lib/puppet/functions/to_json.rb
  lib/puppet/functions/to_yaml.rb
  spec/functions/to_yaml_spec.rb
Labels: bugfix, community

#1235 (MODULES-4976) Add windows escaping functions
  lib/puppet/parser/functions/batch_escape.rb
  lib/puppet/parser/functions/powershell_escape.rb
  spec/functions/batch_escape_spec.rb
  spec/functions/powershell_escape_spec.rb
Labels: feature, community

#1232 (maint) Update str2saltedpbkdf2.rb to use the correct salt length
  lib/puppet/parser/functions/str2saltedpbkdf2.rb
Labels: community
