Repository puppetlabs/puppetlabs-stdlib, pull requests merged in 2022-10, with the labels that each got.

#1269 pdksync - (CONT-130) - Dropping Support for Debian 9
  metadata.json
Labels: bugfix, hacktoberfest

#1271 pdksync - (PDKSync) Removal of puppet_module_gems
  .devcontainer/README.md
  Gemfile
  metadata.json
Labels: maintenance, hacktoberfest

#1272 pdksync - (CONT-189) Remove support for RedHat6 / OracleLinux6 / Scientific6
  metadata.json
Labels: bugfix, hacktoberfest

#1275 (CONT-200) Fix require relative paths
  lib/puppet_x/stdlib/toml_dumper.rb
Labels: bugfix

#1280 Drop Puppet < 3.6 support in package_provider fact
  lib/facter/package_provider.rb
Labels: community

#1278 Determine root_home without shelling out
  lib/facter/root_home.rb
  spec/unit/facter/root_home_spec.rb
Labels: community

#1279 Correct bcrypt salt regex
  lib/puppet/parser/functions/pw_hash.rb
  spec/functions/pw_hash_spec.rb
Labels: community
