Repository puppetlabs/puppetlabs-stdlib, pull requests merged in 2022-05, with the labels that each got.

#1241 Update load_module_metadata.rb to correct capitalisation in strings documentartion
  lib/puppet/parser/functions/load_module_metadata.rb
Labels: bugfix

#1205 Fix serialization of undef in to_python()
  lib/puppet/functions/to_python.rb
  lib/puppet/functions/to_ruby.rb
  spec/functions/to_python_spec.rb
  spec/functions/to_ruby_spec.rb
Labels: bugfix, community

#1233 MODULES-11309 : convert a string to a resource
  README.md
  lib/puppet/functions/stdlib/str2resource.rb
  manifests/init.pp
  manifests/manage.pp
  spec/classes/manage_spec.rb
  spec/functions/str2resource_spec.rb
Labels: community

#1236 Add `xml_encode` function
  REFERENCE.md
  lib/puppet/functions/stdlib/xml_encode.rb
  spec/functions/xml_encode_spec.rb
Labels: community

#1238 Modernize escape functions
  lib/puppet/functions/batch_escape.rb
  lib/puppet/functions/powershell_escape.rb
  lib/puppet/functions/shell_escape.rb
  lib/puppet/parser/functions/batch_escape.rb
  lib/puppet/parser/functions/powershell_escape.rb
  lib/puppet/parser/functions/shell_escape.rb
  spec/functions/batch_escape_spec.rb
  spec/functions/powershell_escape_spec.rb
  spec/functions/shell_escape_spec.rb
Labels: community
