Repository puppetlabs/puppetlabs-stdlib, pull requests merged in 2022-07, with the labels that each got.

#1244 Convert `ensure_packages` to new API and refactor
  REFERENCE.md
  lib/puppet/functions/ensure_packages.rb
  lib/puppet/parser/functions/ensure_packages.rb
  spec/functions/ensure_packages_spec.rb
Labels: community

#1250 Simplify stdlib::manage
  README.md
  manifests/manage.pp
  spec/classes/manage_spec.rb
Labels: bugfix, community

#1240 Switch parsejson() from PSON to JSON parsing
  lib/puppet/parser/functions/parsejson.rb
  spec/functions/parsejson_spec.rb
Labels: bugfix, community

#1259 (FEAT) Add function parsepson
  REFERENCE.md
  lib/puppet/functions/parsepson.rb
  spec/functions/parsepson_spec.rb
Labels: feature
