Repository puppetlabs/puppetlabs-stdlib, pull requests merged in 2023-04, with the labels that each got.

#1305 pdksync - (CONT-844) - Update .sync.yml
  .sync.yml
Labels: maintenance

#1308 (PUP-11752) Fix fqdn_rand_string_spec.rb test
  spec/functions/fqdn_rand_string_spec.rb
Labels: community

#1300 Make ensure_packages work with `ensure => present`
  lib/puppet/functions/ensure_packages.rb
  spec/functions/ensure_packages_spec.rb
Labels: community

#1299 Stdlib::Http::Method: Add new type for http methods
  REFERENCE.md
  spec/type_aliases/http__method_spec.rb
  spec/type_aliases/http__status_spec.rb
  types/http/method.pp
  types/http/status.pp
  types/httpstatus.pp
Labels: community

#1309 Remove deprecated type and type3x functions
  lib/puppet/parser/functions/type.rb
  lib/puppet/parser/functions/type3x.rb
  spec/functions/type3x_spec.rb
  spec/functions/type_spec.rb
Labels: backwards-incompatible

#1310 Remove deprecated Private function
  lib/puppet/parser/functions/private.rb
  spec/functions/private_spec.rb
Labels: backwards-incompatible

#1314 Remove Puppet 5.5 deprecations
  lib/puppet/functions/length.rb
  lib/puppet/parser/functions/empty.rb
  lib/puppet/parser/functions/flatten.rb
  lib/puppet/parser/functions/join.rb
  lib/puppet/parser/functions/keys.rb
  lib/puppet/parser/functions/values.rb
  spec/functions/empty_spec.rb
  spec/functions/flatten_spec.rb
  spec/functions/join_spec.rb
  spec/functions/keys_spec.rb
  spec/functions/length_spec.rb
  spec/functions/values_spec.rb
Labels: backwards-incompatible

#1311 Remove deprecated unique function
  lib/puppet/parser/functions/unique.rb
  spec/functions/unique_spec.rb
Labels: backwards-incompatible

#1316 Remove dig and dig44 functions
  lib/puppet/parser/functions/dig.rb
  lib/puppet/parser/functions/dig44.rb
  lib/puppet/parser/functions/try_get_value.rb
  spec/functions/dig44_spec.rb
  spec/functions/dig_spec.rb
  spec/functions/try_get_value_spec.rb
Labels: backwards-incompatible

#1317 Remove deprecated abs function
  lib/puppet/parser/functions/abs.rb
  spec/functions/abs_spec.rb
Labels: backwards-incompatible

#1318 Remove deprecated downcase function
  lib/puppet/parser/functions/downcase.rb
  spec/functions/downcase_spec.rb
Labels: backwards-incompatible

#1319 Remove deprecated has_key function
  lib/puppet/parser/functions/has_key.rb
  spec/functions/has_key_spec.rb
Labels: backwards-incompatible

#1340 (maint) - Add litmus ~> 1.0
  Gemfile
Labels: maintenance

#1321 Remove deprecated lstrip function
  lib/puppet/parser/functions/lstrip.rb
  spec/functions/lstrip_spec.rb
Labels: backwards-incompatible

#1322 Remove deprecated max function
  lib/puppet/parser/functions/max.rb
  spec/functions/max_spec.rb
Labels: backwards-incompatible

#1323 Remove deprecated min function
  lib/puppet/parser/functions/min.rb
  spec/functions/min_spec.rb
Labels: backwards-incompatible

#1326 Modernise `has_interface_with` function
  REFERENCE.md
  lib/puppet/functions/has_interface_with.rb
  lib/puppet/functions/stdlib/has_interface_with.rb
  spec/functions/has_interface_with_spec.rb
Labels: backwards-incompatible, community

#1327 Remove deprecated camelcase function
  lib/puppet/parser/functions/camelcase.rb
  spec/functions/camelcase_spec.rb
Labels: backwards-incompatible, community

#1329 Remove deprecated ceiling function
  lib/puppet/parser/functions/ceiling.rb
  spec/functions/ceiling_spec.rb
Labels: backwards-incompatible, community

#1328 Remove deprecated capitalize functions
  lib/puppet/parser/functions/capitalize.rb
  spec/functions/capitalize_spec.rb
Labels: backwards-incompatible, community

#1324 Remove deprecated is_absolute_path function
  lib/puppet/functions/is_absolute_path.rb
  lib/puppet/parser/functions/is_absolute_path.rb
  spec/functions/validate_absolute_path_spec.rb
  spec/unit/puppet/parser/functions/is_absolute_path_spec.rb
Labels: backwards-incompatible

#1325 Remove deprecated is_array function
  lib/puppet/functions/is_array.rb
  lib/puppet/parser/functions/is_array.rb
  spec/functions/is_array_spec.rb
Labels: backwards-incompatible

#1330 Remove deprecated chomp function
  lib/puppet/parser/functions/chomp.rb
  spec/functions/chomp_spec.rb
Labels: backwards-incompatible, community

#1331 Remove deprecated chop function
  lib/puppet/parser/functions/chop.rb
  spec/functions/chop_spec.rb
Labels: backwards-incompatible, community

#1333 Remove deprecated round function
  lib/puppet/parser/functions/round.rb
  spec/functions/round_spec.rb
Labels: backwards-incompatible, community

#1334 Remove deprecated upcase function
  lib/puppet/parser/functions/upcase.rb
  spec/functions/upcase_spec.rb
Labels: backwards-incompatible, community

#1335 Remove deprecated sort function
  lib/puppet/parser/functions/sort.rb
  spec/functions/sort_spec.rb
Labels: backwards-incompatible, community

#1336 Remove deprecated getvar function
  lib/puppet/parser/functions/getvar.rb
  spec/functions/getvar_spec.rb
Labels: backwards-incompatible, community

#1337 Remove deprecated rstrip function
  lib/puppet/parser/functions/rstrip.rb
  spec/functions/rstrip_spec.rb
Labels: backwards-incompatible, community

#1338 Remove deprecated strip function
  lib/puppet/parser/functions/strip.rb
  spec/functions/strip_spec.rb
Labels: backwards-incompatible, community
