Repository puppetlabs/puppetlabs-stdlib, pull requests merged in 2023-06, with the labels that each got.

#1362 re-add support for loading aliases in yaml files
  lib/puppet/parser/functions/loadyaml.rb
  spec/functions/loadyaml_spec.rb
Labels: community

#1367 Fix `fqdn_rand_string` regression
  lib/puppet/functions/stdlib/fqdn_rand_string.rb
  spec/functions/fqdn_rand_string_spec.rb
Labels: bugfix, community

#1370 (CONT-1035) Alter logic of pw_hash
  lib/puppet/parser/functions/pw_hash.rb
Labels: bugfix

#1372 pdksync - (CONT-990) - Adding Community Pull Requests template
  .github/pull_request_template.md
Labels: maintenance

#1366 Pass calling scope to `stdlib::ensure_packages` from shim
  Rakefile
  lib/puppet/functions/ensure_packages.rb
Labels: bugfix, community

#1378 Add `use_strict_setting` parameter to `deprecation` function
  lib/puppet/functions/deprecation.rb
  spec/functions/deprecation_spec.rb
Labels: feature, community

#1377 Ignore Puppet's `strict` setting when calling function without namespace
  Rakefile
  lib/puppet/functions/batch_escape.rb
  lib/puppet/functions/ensure_packages.rb
  lib/puppet/functions/fqdn_rand_string.rb
  lib/puppet/functions/has_interface_with.rb
  lib/puppet/functions/merge.rb
  lib/puppet/functions/os_version_gte.rb
  lib/puppet/functions/parsehocon.rb
  lib/puppet/functions/powershell_escape.rb
  lib/puppet/functions/seeded_rand.rb
  lib/puppet/functions/seeded_rand_string.rb
  lib/puppet/functions/shell_escape.rb
  lib/puppet/functions/to_json.rb
  lib/puppet/functions/to_json_pretty.rb
  lib/puppet/functions/to_python.rb
  lib/puppet/functions/to_ruby.rb
  lib/puppet/functions/to_toml.rb
  lib/puppet/functions/to_yaml.rb
  lib/puppet/functions/type_of.rb
  lib/puppet/functions/validate_domain_name.rb
  lib/puppet/functions/validate_email_address.rb
Labels: bugfix, community
