Repository puppetlabs/puppetlabs-stdlib, pull requests merged in 2023-05, with the labels that each got.

#1348 Add Stdlib::IP::Address::CIDR
  types/ip/address/cidr.pp
Labels: community

#1343 Rewrite fqdn_rand_string() as a Puppet 4.x function
  lib/puppet/functions/fqdn_rand_string.rb
  lib/puppet/parser/functions/fqdn_rand_string.rb
  spec/functions/fqdn_rand_string_spec.rb
Labels: community, MayTheSourceBeWithYou

#1344 Rewrite seeded_rand() as a Puppet 4.x function
  lib/puppet/functions/seeded_rand.rb
  lib/puppet/parser/functions/seeded_rand.rb
  spec/functions/seeded_rand_spec.rb
Labels: community, MayTheSourceBeWithYou

#1345 Rewrite validate_domain_name() as a Puppet 4.x function
  lib/puppet/functions/validate_domain_name.rb
  lib/puppet/parser/functions/validate_domain_name.rb
  spec/functions/validate_domain_name_spec.rb
  spec/type_aliases/dns_zone_spec.rb
  spec/type_aliases/fqdn_spec.rb
  spec/type_aliases/host_spec.rb
  types/dns/zone.pp
Labels: community, MayTheSourceBeWithYou

#1351 Fix validate_domain_name called without parameters
  lib/puppet/functions/validate_domain_name.rb
  spec/functions/validate_domain_name_spec.rb
Labels: bugfix, community, MayTheSourceBeWithYou

#1350 Rewrite validate_email_address() as a Puppet 4.x function
  lib/puppet/functions/validate_email_address.rb
  lib/puppet/parser/functions/validate_email_address.rb
  spec/functions/validate_email_address_spec.rb
Labels: community, MayTheSourceBeWithYou

#1342 Allow `deferrable_epp` to return a `Sensitive[String]`
  functions/deferrable_epp.pp
Labels: community

#1353 Deprecate the `validate_legacy()` function
  lib/puppet/functions/validate_legacy.rb
  spec/functions/validate_legacy_spec.rb
Labels: community

#1355 pdksync - (CONT-930) - Roll out new changelog generator
  .github/release_prep.yml
  .github/workflows/auto_release.yml
Labels: maintenance

#1357 Remove deprecated File.exists?
  lib/puppet/parser/functions/load_module_metadata.rb
  lib/puppet/parser/functions/loadjson.rb
  lib/puppet/parser/functions/loadyaml.rb
  spec/functions/load_module_metadata_spec.rb
  spec/functions/loadjson_spec.rb
  spec/functions/loadyaml_spec.rb
Labels: community

#1356 Namespace Puppet 4.x functions
  .rubocop_todo.yml
  Rakefile
  lib/puppet/functions/batch_escape.rb
  lib/puppet/functions/ensure_packages.rb
  lib/puppet/functions/fqdn_rand_string.rb
  lib/puppet/functions/has_interface_with.rb
  lib/puppet/functions/merge.rb
  lib/puppet/functions/os_version_gte.rb
  lib/puppet/functions/parsehocon.rb
  lib/puppet/functions/powershell_escape.rb
  lib/puppet/functions/seeded_rand.rb
  lib/puppet/functions/seeded_rand_string.rb
  lib/puppet/functions/shell_escape.rb
  lib/puppet/functions/stdlib/batch_escape.rb
  lib/puppet/functions/stdlib/ensure_packages.rb
  lib/puppet/functions/stdlib/fqdn_rand_string.rb
  lib/puppet/functions/stdlib/merge.rb
  lib/puppet/functions/stdlib/os_version_gte.rb
  lib/puppet/functions/stdlib/parsehocon.rb
  lib/puppet/functions/stdlib/powershell_escape.rb
  lib/puppet/functions/stdlib/seeded_rand.rb
  lib/puppet/functions/stdlib/seeded_rand_string.rb
  lib/puppet/functions/stdlib/shell_escape.rb
  lib/puppet/functions/stdlib/to_json.rb
  lib/puppet/functions/stdlib/to_json_pretty.rb
  lib/puppet/functions/stdlib/to_python.rb
  lib/puppet/functions/stdlib/to_ruby.rb
  lib/puppet/functions/stdlib/to_toml.rb
  lib/puppet/functions/stdlib/to_yaml.rb
  lib/puppet/functions/stdlib/type_of.rb
  lib/puppet/functions/stdlib/validate_domain_name.rb
  lib/puppet/functions/stdlib/validate_email_address.rb
  lib/puppet/functions/to_json.rb
  lib/puppet/functions/to_json_pretty.rb
  lib/puppet/functions/to_python.rb
  lib/puppet/functions/to_ruby.rb
  lib/puppet/functions/to_toml.rb
  lib/puppet/functions/to_yaml.rb
  lib/puppet/functions/type_of.rb
  lib/puppet/functions/validate_domain_name.rb
  lib/puppet/functions/validate_email_address.rb
  spec/functions/batch_escape_spec.rb
  spec/functions/ensure_packages_spec.rb
  spec/functions/fqdn_rand_string_spec.rb
  spec/functions/merge_spec.rb
  spec/functions/os_version_gte_spec.rb
  spec/functions/parsehocon_spec.rb
  spec/functions/powershell_escape_spec.rb
  spec/functions/seeded_rand_spec.rb
  spec/functions/seeded_rand_string_spec.rb
  spec/functions/shell_escape_spec.rb
  spec/functions/to_json_pretty_spec.rb
  spec/functions/to_json_spec.rb
  spec/functions/to_python_spec.rb
  spec/functions/to_ruby_spec.rb
  spec/functions/to_toml_spec.rb
  spec/functions/to_yaml_spec.rb
  spec/functions/type_of_spec.rb
  spec/functions/validate_domain_name_spec.rb
  spec/functions/validate_email_address_spec.rb
Labels: community

#1359 (CONT-1023) - Enhancing deferrable_epp to support nested hash
  functions/deferrable_epp.pp
  lib/puppet/functions/nested_values.rb
  spec/functions/nested_values_spec.rb
Labels: maintenance
