Repository puppetlabs/puppetlabs-stdlib, pull requests merged in 2023-03, with the labels that each got.

#1281 Add Stdlib::Ensure::Package type
  spec/type_aliases/ensure_package_spec.rb
  types/ensure/package.pp
Labels: feature, community

#1295 Safely handle a missing root user
  lib/facter/root_home.rb
Labels: bugfix, community

#1301 REFERENCE.md: apply fix for unique anchors from puppet strings
  REFERENCE.md
Labels: community

#1302 pdksync - (CONT-768) Pin puppetlabs-puppet_agent
  .fixtures.yml
Labels: maintenance
